# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wagers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wager', models.CharField(max_length=5)),
            ],
        ),
    ]
